### PR TITLE
Clean up distribution collection

### PR DESCRIPTION
**Pull request by jonathf**
* Switch to a consistent name convention for distribution using title case, e.g. `Lognormal -> LogNormal`. In this update, old distribution is kept, but raises a warning for the user.
* Split each distribution into own file.
* Doctest coverage for all distributions!
* New distribution string representation convension. Instead of customizing using `_str` method, distributions are now initialized with a `._repr` dictionary.
* Update to documentation on how to handle distributions.

### CODE REVIEW

**Comment by flo2k** [comment]
I'm just testing the changes with my code. I do now have an issue with `Sens_m`.

This code runs with latest version of `develpment` branch.

```python
import chaospy as cp
import numpy as np

dist = cp.J(cp.Normal(0, 1), cp.Uniform(0, 5))
vals = dist.sample(500)[0]

print(vals.shape)


nodes, weights = cp.generate_quadrature(5, dist, rule='G')
nodes = nodes[0]

# solver
def solver(n):
    return np.sum(n)


solves = [solver(n) for n in nodes]
print(solves)

P = cp.orth_ttr(2, dist)
U = cp.fit_quadrature(P, nodes, weights, solves)

sm = cp.Sens_m(U, dist)
print(sm)
```

With the version in the `dist_clean` branch I do get the following errors:
```
Traceback (most recent call last):
  File "/data/repos/repos_tum/promotion.git/warmup/Python/uq_general_tests/sens/test_sens.py", line 24, in <module>
    sm = cp.Sens_m(U, dist)
  File "/data/repos/repos_tum/chaospy.git/src/chaospy/descriptives/sensitivity.py", line 27, in Sens_m
    dist, **kws)/(V+(V == 0))*(V != 0)
  File "/data/repos/repos_tum/chaospy.git/src/chaospy/descriptives/first.py", line 74, in E_cond
    assert not dist.dependent()
AttributeError: 'J' object has no attribute 'dependent'
```

**Comment by jonathf** [comment]
Thanks. I'll take a look at it over this weekend.

**Comment by jonathf** [comment]
@flo2k, try now.

**Comment by flo2k** [comment]
Most of my code runs now. I did a small improvement, inside the `sample_dist.py`, because of parameter names and includes changed.

**Comment by flo2k** [comment]
With new folder structure how can I construct a custom dist with the `custom()` function?

I thought at some time this code was running:
```python
import chaospy as cp
import numpy as np

MyUniform = cp.distributions.baseclass.construct(
    cdf=lambda self, x, lo, up: (x - lo) / (up - lo),
    bnd=lambda self, lo, up: (lo, up)
)

uniform = MyUniform(lo=-1, up=1)
t = np.linspace(-10, 20, 50)

vals = uniform.pdf(t)
print(vals)
```

**Comment by jonathf** [comment]
I've fixed it up and pushed the changes. A small change in syntax is required though. I've added docs for how to use it now:
```
Custom distribution constructor.

Example usage
-------------

Construct distribution from scratch::

    >>> MyUniform = chaospy.construct(
    ...     cdf=lambda self, x, lo, up: (x - lo) / (up - lo),
    ...     bnd=lambda self, x, lo, up: (lo, up)
    ... )

Evaluate distribution::

    >>> uniform = MyUniform(lo=-1, up=1)
    >>> print(uniform.pdf(numpy.linspace(-2, 2, 16)))
    [0.  0.  0.  0.  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.  0.  0.  0. ]
```

**Comment by jonathf** [comment]
The new `x` arg for `bnd` is needed when doing multivariate distributions and you need to change the bounds given dependencies. Mostly not used.

**Comment by flo2k** [comment]
Do I miss something?

```python
import chaospy as cp
import numpy as np

MyUniform = cp.construct(
    cdf=lambda self, x, lo, up: (x - lo) / (up - lo),
    bnd=lambda self, lo, up: (lo, up)
)

uniform = MyUniform(lo=-1, up=1)
print(uniform.pdf(np.linspace(-2, 2, 16)))
```
I do get the following error:
```
Traceback (most recent call last):
  File "/data/repos/repos_tum/promotion.git/warmup/Python/uq_general_tests/tests_qoi_dist/error_custom_dist.py", line 10, in <module>
    print(uniform.pdf(np.linspace(-2, 2, 16)))
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/baseclass.py", line 240, in pdf
    eps=step)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/baseclass.py", line 198, in run
    return main.call(self, x, mode, **meta)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/main.py", line 61, in call
    out = self(x_data, self.root)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/baseclass.py", line 160, in __call__
    return self._call(self, *args, **kwargs)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/calling/pdf.py", line 32, in pdf_call
    out = approx.pdf(dist, x_data, self, **self.meta)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/approx.py", line 58, in pdf
    G.__call__ = G.fwd_call
AttributeError: 'Graph' object has no attribute 'fwd_call'
```

**Comment by flo2k** [comment]
With the `x`

```python
import chaospy as cp
import numpy as np

MyUniform = cp.construct(
    cdf=lambda self, x, lo, up: (x - lo) / (up - lo),
    bnd=lambda self, x, lo, up: (lo, up)
)

uniform = MyUniform(lo=-1, up=1)
print(uniform.pdf(np.linspace(-2, 2, 16)))
```
I do get the following error:
```
Traceback (most recent call last):
  File "/data/repos/repos_tum/promotion.git/warmup/Python/uq_general_tests/tests_qoi_dist/error_custom_dist.py", line 10, in <module>
    print(uniform.pdf(np.linspace(-2, 2, 16)))
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/baseclass.py", line 233, in pdf
    (lo, up), graph = self.graph.run(x, "range")
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/baseclass.py", line 198, in run
    return main.call(self, x, mode, **meta)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/main.py", line 61, in call
    out = self(x_data, self.root)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/baseclass.py", line 160, in __call__
    return self._call(self, *args, **kwargs)
  File "/data/repos/repos_tum/chaospy_run.git/src/chaospy/distributions/graph/calling/range_.py", line 29, in range_call
    lower, upper = dist._bnd(**prm)
TypeError: <lambda>() missing 1 required positional argument: 'x'
```

**Comment by jonathf** [comment]
I am not replicating that behavior. Are you on the `clean_dist` branch. The `self.graph.run(x, "range")` exists in `development`, but not in the new branch.

**Comment by flo2k** [comment]
It seems, that my branch was not clean. I checked did a clean checkout and this works now.

But, I observed something else. `sample_dist.sample()` seems to be very slow now. 

If I run this code with the `development` branch:
```python
import chaospy as cp
import datetime

dist = cp.Normal(0, 1)

samples = dist.sample(1e4)
sample_dist = cp.SampleDist(samples)

start = datetime.datetime.now()
qoi_dist_samples = sample_dist.sample(1e3)
end = datetime.datetime.now()

delta = end - start

print("elapsed time: %d microseconds" % (delta.microseconds))
```

I do get this output:
```
elapsed time: 245 microseconds

Process finished with exit code 0
```

If I run the same code with the `clean_dist` branch I get the following runtime:
```
elapsed time: 226169 microseconds

Process finished with exit code 0
```

Do you think there is a way to speed this up?

**Comment by jonathf** [comment]
Of course. I removed the `sample` method to make sure #95 would work.
Now that we've confirmed that, I have added it back.

**Pull request merged**
