### PR TITLE
Multivariate Kernel Density Estimation

### PR DESCRIPTION
**Pull request by jonathf**
So this has been in the pipes a while now, but I haven't gotton around to it before now.

I haven't finalized the function signature, nor the code, but this is the first working version, so I definetly be working on it a little more before merging, but it should be operational.

I quickly thrown together some code showing what it is all about:
https://chaospy.readthedocs.io/en/docs/tutorials/advanced/kernel_density_estimation.html

### CODE REVIEW

**Comment by jonathf** [comment]
@Jingfei-liu, @flo2k, @ar-valdez, @AnnaCraig,
this might be of interest to some of you. Any and all input are welcome.

**Comment by ar-valdez** [comment]
Dear @jonathf, thanks for the tag.

Indeed this is very interesting, specially when you don't know the distribution of the input parameters....... Let me ask you the following:

1) With the `GaussianKDE(your samples)` you create the distribution that ChaosPy will use to do the UQ-SA, and other studies......, the question is "I can use a distribution created before, and fit any kind of models in that distribution data-set? Where is the dependency between the distribution and input parameters?
2) Trying to answer the previous question  Can I call `GaussianKDE()` for each input parameter and after execute with normal flow?

**Comment by jonathf** [comment]
1. Good question. Multivariate KDE breaks the normal UQ-SA tools. However, there is a solution to this described here:
  https://hal.archives-ouvertes.fr/hal-01182302/file/Mara15EMS_HAL.pdf
  I will see if I can update the `Sens_*_sample` functions to support this algorithm.
2. I haven't tried, but I don't see why not. But note that this is equivalent to using the already implemented `chaospy.SampleDist`, as it is 1-D KDE.

**Comment by jonathf** [comment]
@ar-valdez,

So working through the paper now and trying to make it work and hit a snag. I realized I need to be able to rotate dependencies to be able to extract all SA indices numerically. I don't have that feature, but it is something I have wanted to implement a while now, so it will likely something I'll get around to before the end of the year.

Short term however, I've added a small patch, so you can extract SA metrics by rotation yourself. E.g.

```python
variables = chaospy.variables(len(samples))
for idx in range(len(samples)):

    # rotate dimensions in samples, distribution and approx-model
    samples_ = numpy.vstack([samples[:idx], samples[idx:]])
    dist_ = chaospy.GaussianKDE(samples_)
    model_approx_ = model_approx(*chaospy.hstack([variables[:idx] variables[idx:]])

    # calculate indices, but only use the left most one
    main = chaospy.Sens_m_sample(model_approx_, dist_, samples=10000, rule="halton")
    print(f"main Sobol for dim {idx}: {main[0]}")
    total = chaospy.Sens_t_sample(model_approx_, dist_, samples=10000, rule="halton")
    print(f"total Sobol for dim {idx}: {total[0]}")
```
The main takeaway is that only the first sensetivity index is correct, and you need to rotate the data and how the model approximation recieves the data such that the index of interest is moved to the front.

The second order indices should also be possible, but require more index trickery.

**Comment by Jingfei-Liu** [comment]
It is absolutely a beautiful action,  thanks for releasing such an amazing tool. I will keep up with this update, and give my feedback.

**Comment by flo2k** [comment]
> @Jingfei-Liu, @flo2k, @ar-valdez, @AnnaCraig,
> this might be of interest to some of you. Any and all input are welcome.

@jonathf thanks for that hint. This is indeed very interesting for me. But right now, I'm very busy: finishing and submitting the thesis, and preparing lectures. Hopefully, I can give it a try in the next weeks.

**Comment by jonathf** [comment]
So I've made an update:
* Argument `bandwidth2` is updated to `covariance`, as is what it is.
* Sequence of covariances is now allowed.
* I've added a optional `weights` argument that says the weight each sample should.

@Jingfei-Liu, I am bringing in the conversation from #269:

KDE and GMM are quite similar. KDE is GMM taken to the extreme sample wise, while GMM assumes full mean/covariance control for each sample. In other words, this update should allow you to do GMM in chaospy.

Note that if `samples.shape=(D, K)`, then covariance must be at most `(K, D, D)`. In other words, as a GMM replacement, the two parameters are transposed. I'll make a GMM wrapper to fix this.

**Comment by jonathf** [comment]
Tutorial/Demo link updated to include per-sample-covariances demonstrating the models capabilities to mimic GMM:
https://chaospy.readthedocs.io/en/docs/tutorials/advanced/kernel_density_estimation.html

**Comment by jonathf** [comment]
KDE is now added to the release `4.0-beta2`. Its call signature is adjusted a little bit.
Docs are also updated.

Other kernels and Mixture-Models on the horizon.

**Comment by ar-valdez** [comment]
Dear @jonathf this will be available on pip also?

Thanks for developing this feature. It will be very useful to perform data-driven PCE studies.

Bests.-

**Comment by jonathf** [comment]
Yes, but it is flagged as beta, so you will need to do `pip install chaospy==4.0b2`.

There is another larger refactoring going on in the 4.0 release, and I'd like to do a little more testing before releasing it as the installation default. But it is coming.

**Comment by Jingfei-Liu** [comment]
@jonathf  It is admirable to relaease this important sourcecode. Thanks so much!

**Pull request merged**
