### PR TITLE
Added example how to solve SEIR model using Chaospy

### PR DESCRIPTION
**Pull request by Novermars**
This notebook shows how to solve the SEIR model in epidemiology with uncertain parameters, it also shows how Chaospy can be used to solve differential equations.

### CODE REVIEW

**Comment by jonathf** [comment]
Thanks, I really appriciate it.

1. I don't know what SEIR actually is. I just see equations to be solved. Would it perhaps be possible to expand the intro part explaining what SEIR is and where the reader perhaps could find resources to read more up on the topic?
2. To make the notebook visible and available, `docs/tutorial/index.rst` needs to be updated with new TOC entry, link to the tutorial and a small intro-text (similar to the expanded intro).
3. I also prefer to let the code pass pep8 linting rules when displyed in the docs, but not important to get the code merged now.

I can do 2 and 3 myself, but I need your help with 1. Do you mind helping out?

**Comment by Novermars** [comment]
Let me know if this is sufficient, I think it's better if you can do 2 and 3!

**Comment by jonathf** [comment]
Okay. I'll take a look at the changes when I have a moment.

Do you mind giving me [write access to the remote](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so I can push changes?

**Comment by jonathf** [comment]
I've updated the TOC/index and the notebook. I've also taken the liberty to rephrase the introduction a little and to structure the notebook to the form similar to the rest of the tutorials. Mostly just moved the comments into their own markdown fields.

I've added a link to the wikipedia article. Let me know if you have better sources for describing the overall topic.

**Comment by Novermars** [comment]
I unfortunately don't have a better source, I was trying to write [this julia notebook](https://nbviewer.jupyter.org/github/djsegal/SimplePlots.jl/blob/master/binder/covid-19.ipynb) in python using PCE.

Otherwise it's looking good!

**Comment by jonathf** [comment]
Okay, great. And again: thanks for your contribution.

**Pull request merged**
