### PR TITLE
Gaussian Mixture Models

### PR DESCRIPTION
**Pull request by jonathf**
Mostly docs as GMM is using the new GaussianKDE in the backend.

Tutorial preview:
https://chaospy.readthedocs.io/en/docs/tutorials/advanced/gaussian_mixture_model.html

### CODE REVIEW

**Comment by jonathf** [comment]
@coschroeder, @GithubBlues, @Jingfei-Liu,

you guys have noted interest in GMM (or dependent modelling). If still the case check out the link above, and if you want to try it out locally, install with:
`pip install git+https://github.com/jonathf/chaospy.git@gmm`

**Comment by Jingfei-Liu** [comment]
@jonathf It is an exciting development, it is exactly convenient for me, thank you very much!

**Comment by Jingfei-Liu** [comment]
@jonathf  I also think Chaospy is a nice tutorial materials for researchers, students and engineers. It is user friendly, and readable. So it should  be propagated more extensively. At least, I will introduce it to my friends and I will cite the corresponding papers in my work.

**Comment by coschroeder** [comment]
@jonathf cool, thanks a lot for this development. just in time to update some experiments and include into a manuscript!

**Pull request merged**
