### PR TITLE
change the order and det calc

### PR DESCRIPTION
**Pull request by ma6yu**
hi,
I changed the order calculation and the determinant calculations. please check the lagrange.py (ignore the history files, I have no idea how to delete them, sorry...)
If you write:

```
nodes = np.array([[0.,2.,1.,-2.,-3., -1.], [1.,1.,3.,-1.,2.,2,]])
Lagrange = cp.lagrange_polynomial(nodes)
print(Lagrange(*nodes))
```

it gives:
[[  1.00000000e+00   2.44249065e-15   7.93809463e-15   3.33066907e-15
   -6.66133815e-15  -2.72004641e-15]
 [ -1.66533454e-15   1.00000000e+00  -9.55485691e-15   2.85882429e-15
   -5.66213743e-15  -5.78009862e-15]
 [  7.77156117e-16   7.77156117e-16   1.00000000e+00  -2.33146835e-15
    3.99680289e-15   2.58126853e-15]
 [ -5.55111512e-17  -1.11022302e-15  -2.74780199e-15   1.00000000e+00
    5.55111512e-16  -4.16333634e-16]
 [ -9.99200722e-16  -1.33226763e-15  -6.66133815e-15   1.77635684e-15
    1.00000000e+00  -2.22044605e-15]
 [ -1.33226763e-15  -4.44089210e-15  -8.43769499e-15  -8.88178420e-16
   -8.88178420e-15   1.00000000e+00]]

### CODE REVIEW

**Comment by ma6yu** [comment]
This code still have problem if I increase number of samples.
The problem is,
if I write

```
indices = np.array(cp.bertran.bindex(0, 4, 2, "G"))
vec = cp.poly.basis(0, 4, 2, "G")
print(indices)
print(vec)
```

I was expecting:
[[0 0]
 [0 1]
 [1 0]
 [0 2]
 [1 1]
 [2 0]
 [0 3]
 [1 2]
 [2 1]
 [3 0]
 [0 4]
 [1 3]
 [2 2]
 [3 1]
 [4 0]]
[1, q1, q0, q1^2, q0q1, q0^2, q1^3, q0q1^2, q0^2q1, q0^3, q1^4, q0q1^3, q0^2q1^2, q0^3q1, q0^4]

But I got:
[[0 0]
 [0 1]
 [1 0]
 [0 2]
 [1 1]
 [2 0]
 [0 3]
 [1 2]
 [2 1]
 [3 0]
 [0 4]
 [1 3]
 [2 2]
 [3 1]
 [4 0]]
[1, q1, q0, q0q1, q0^2, q1^2, q0^3, q0^2q1, q1^3, q0q1^2, q0^3q1, q0q1^3, q0^2q1^2, q0^4, q1^4]

Should the sequence of the indices be same between indices and vec, if the "sort" is same?

**Comment by ma6yu** [comment]
I am afraid it doesn't...
It gives different ones as before but still the sequence are not same between indices and vec.
Now I got
[[0 0]
 [1 0]
 [0 1]
 [2 0]
 [1 1]
 [0 2]
 [3 0]
 [2 1]
 [1 2]
 [0 3]
 [4 0]
 [3 1]
 [2 2]
 [1 3]
 [0 4]]
[1, q0, q1, q0^2, q1^2, q0q1, q0^3, q1^3, q0q1^2, q0^2q1, q0q1^3, q1^4, q0^2q1^2, q0^4, q0^3q1]

**Comment by jonathf** [comment]
okay, Ill take closer look.

**Comment by jonathf** [comment]
That is a sneaky little bug. The `numpy.argsort` isn't consistent as an array is extended. I didn't know that.

I've updated #179 to use `numpy.lexsort` instead. Should do the trick.

**Comment by jonathf** [comment]
No worries about the time usage. This is a hobby project for me, and any help that I can get is a bonus. Thank you for taking the time to do this at all.

This looks good, but I prefer not to include all the `.history/` files you have included. Remove those, and I'll merge afterwards.

**Pull request merged**
